name: Self Test

on:
  push:
  workflow_dispatch:

jobs:
  platforms:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Self Test Setup
        id: selftest
        uses: ./
        with:
          access_key: DUMMY_KEY
          secret_key: DUMMY_SECRET
      - name: Test Binary
        run: |
          sup3 --version
      - name: Test Path
        run: |
          ${{ steps.selftest.outputs.path }}/sup3 --version
      - name: Test Env
        if: runner.os != 'Windows'
        run: |
          $SUP3_BIN --version
      - name: Test Env Windows
        if: runner.os == 'Windows'
        run: |
          & $Env:SUP3_BIN --version

      - name: Print config
        run: |
          cat ~/.aws/credentials
