name: Self Test

on:
  push:
  workflow_dispatch:

jobs:
  platforms:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: msys2/setup-msys2@v2
        if: runner.os == 'Windows'
        with:
          release: true
          update: false

      - name: Self Test Setup
        id: selftest
        uses: ./
        with:
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Test Binary
        run: |
          sup3 --version
      - name: Test Path
        run: |
          ${{ steps.selftest.outputs.path }}/sup3 --version

      - name: Print config
        run: |
          cat ~/.aws/credentials

      - name: List Buckets
        run: |
          sup3 list-buckets --region=us-east-1 --endpoint=https://play.min.io:9000

      - name: Test MSys2 Windows
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          sup3 list-buckets --region=us-east-1 --endpoint=https://play.min.io:9000

